title: <p align="center"> Shreyash Nangnurwar </p>
logo: /assets/img/shreyash.jpg

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/shreyashsn/">LinkedIn</a> |
  <a href="https://github.com/ShreyashNangnurwar">GitHub</a>
  
  <br>   
  Software developer with 7+ years experience in design and developing softwares.
  <br>
  </p>



theme: jekyll-theme-minimal
